# Week 2 Assignment: Introduction to Python programming

### Task 1: compute the sum of numbers from 1 to 100 using for loop (2 points)
$$S=\sum_{x=1}^{100}x$$
Hint:
1. There are many ways to solve this problem, However, you are required to use for loop.
2. You may need to set an initial value.

In [5]:
## Type your code below
## Name the sum as s

s = 0
for i in range(1, 101):
    s += i



print(s)

5050

### Task 2: compute the sum of numbers from 1 to 100 using while loop (2 points)
$$S=\sum_{x=1}^{100}x$$
Hint:
1. There are many ways to solve this problem, However, you are required to use while loop.
2. You may need to set an initial value.

In [7]:
## Type your code below
## Name the sum as s

s = 0
i= 0

while i < 101:
    s += i
    i += 1


print(s)

5050

### Task 3: compute the sum of logs of numbers from 1 to 100 (2 points)
$$S=\sum_{x=1}^{100}log(x)$$
Hint:
1. You can use either for loop or while loop or other tricks.
2. You need to import log function from math.

In [9]:
## Type your code below
## Name the sum as s
from math import log

s = 0
for i in range(1, 101):
    i = log(i)
    s += i


print(s)

363.7393755555636

### Task 4: creat a list of numbers from 1 to 100, check the type and then convert the list into a tuple (2 points)

$$l=[1,2,...99,100]$$
Hint and requirements:
1. You should not type all 100 numbers, :-)
2. Name your list as 'l'.
3. Check the type of your list, using    `print('The type of l is:',type(l))`.
4. Create a tuple named 't' that converts l into a tuple.
5. Check the type of your tuple, using    `print('The type of t is:',type(t))`.

In [15]:
## Type your code below

l = list(range(1,101))

print('The type of l is:',type(l))

t = tuple(l)

print('The type of t is:',type(t))

The type of l is: <class 'list'>
The type of t is: <class 'tuple'>

### Task 5: create a list numbers from 1 to 100, using append() and for loop, but do not include number 34,78,89 (2 points)
$$l=[1,2,...,33,35,...,77,79,...,88,90,...,99,100]$$
Hint and requirements:
1. You are not allowed to use list comprehension, :-(
2. Name your list as 'l'.
3. You can first create an empty list, such as, `l=[]`.
4. Append each number from 1 to 100 to the list.
5. If the number is 34,or 78, or 89, do not append.
6. check the number of element in your list using, `len(l)`.

In [22]:
## Type your code below

l = []
for i in range(1,101):
    if i not in (34, 78, 89):
        l.append(i)

print(len(l))

97

### Task 6: use list comprehension to create a list of numbers from 1 to 100, but do not include 34, 78, 89 (2 points)
$$l=[1,2,...,33,35,...,77,79,...,88,90,...,99,100]$$

In [25]:
## Type your code below

l = [i for i in range(1,101) if i not in (34, 78, 89)]
print(l)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100]

### Task 7: use list comprehension to remove stop words from a text (2 points)
`
s="This is an example that stop words can be removed from a text using the list comprehension."
s=s.lower().split()
print(s)
stopwords=['a','this','that','the','be','is','an','can','from']
`
Hint:
1. Create a list (name it as 'new_text') of words from s with stop words removed, using list comprehension.
2. join this list of words back to a string, using: 

`print(' '.join(new))`

In [26]:
s="This is an example that stop words can be removed from a text using the list comprehension."
s=s.lower().split()
print(s)
stopwords=['a','this','that','the','be','is','an','can','from']

## Type your code below
new_text= [i for i in s if i not in (stopwords)]


print(' '.join(new_text))

['this', 'is', 'an', 'example', 'that', 'stop', 'words', 'can', 'be', 'removed', 'from', 'a', 'text', 'using', 'the', 'list', 'comprehension.']
example stop words removed text using list comprehension.

### Task 8: Create a dictionary with keys A, B, C, D, and values 4,3,2,1 respectively (1 point)
Hint:
1. Name the dictionary as 'd'.
2. Print d in the end.

In [29]:
## Type your code below
d = {
    'A': 4,
    'B': 3,
    'C': 2,
    'D': 1
}

print(d)

{'A': 4, 'B': 3, 'C': 2, 'D': 1}

### Task 9: Create a function that calculates the sum of squares of numbers from 1 to x (3 points)
$$f(x)=\sum_{n=1}^{x} n^2$$
Hint:
1. Name your function as SQ(x).
2. Calculate $\sum_{n=1}^{10}n^2$.

In [30]:
## Type your code below

def SQ(x):
    s = 0
    for i in range(1, x+1):
        i = i**2
        s += i
    return s


SQ(10)

385

### Task 10: Create a function f(x) to calculate 180/x, with considering errors (exceptions) (2 points)
$$ f(x)=\frac{180}{x} $$
Hint and requirements:
1. Name your function as 'd_180(x)'.
2. The function does not need to return a value, but has to print the result with '`print('180/'+str(x)+' =',180/x)`'.
3. Use try/except, if caught an exception, print out the exception.
3. run d_180(10), d_180(0),d_180('not a number'),d_180([1]),d_180('90')

In [3]:
## Type your code below
def d_180(x):
    try:
        print('180/'+str(x)+' =',180/x)
    except Exception as e:
        print(e)
        



d_180(10)
d_180(0)
d_180('not a number')
d_180([1])
d_180('90')

180/10 = 18.0
division by zero
unsupported operand type(s) for /: 'int' and 'str'
unsupported operand type(s) for /: 'int' and 'list'
unsupported operand type(s) for /: 'int' and 'str'

## Pandas Basics

### Task 11: Create a pandas dataframe with 100 rows and 4 columns of random numbers. (2 points)
Hint:
1. You need to import pandas as pd.
2. You need to import numpy as np.
3. Use np.random.randn() to generate random number array, but you need to specify rows and columns.
3. Don't need to specify index.
4. Column names are ['A','B','C','D']
6. Name your dataframe as 'df'.

In [14]:
## Type your code below
import pandas as pd
import numpy as np

df = pd.DataFrame(np.random.randn(100,4), columns=['A','B','C','D'])
df

           A         B         C         D
0  -0.140695 -0.070902 -0.745727  2.279679
1  -0.255268  1.258383 -0.345450 -0.794149
2  -0.505161  0.018143 -1.246864  1.463367
3   0.014510 -0.041728  0.266508 -1.206658
4   1.201521 -0.296916 -1.827800  0.647047
5  -0.484932 -0.169802  1.321495  1.086461
6   0.255714  0.356519  1.098574  0.206833
7   0.356424 -1.852580 -0.801042 -0.071295
8   1.270059  1.351365 -1.303072  2.019604
9   0.005959 -2.046826  0.879997 -0.424316
10  1.202771  0.201301  1.092457  0.029396
11 -0.445036  0.712354 -0.117799 -0.667935
12 -1.332635  0.303580 -0.576803 -0.527033
13  0.763835  0.042963  0.408237  0.378144
14  1.449420 -1.439284 -0.492395  1.063746
15  0.818140 -1.097522 -0.696077  0.626603
16 -0.274742 -0.844104 -0.393274  1.120905
17 -0.808849  1.741419  1.207683  1.083034
18  0.983469  0.986837  1.502318 -1.372833
19 -1.954546  0.149933 -0.024339 -0.999220
20 -1.233681 -0.145871 -0.559328  2.072823
21 -0.962003 -1.250003 -0.443778 -2.064275
22  1.112666  0.197965 -1.299121  1.782092
23 -1.317219 -0.864650 -0.363672  0.177945
24  0.740232 -0.247094 -0.280931  0.307330
25 -0.096058  0.553555 -0.823377 -1.244841
26 -1.838482 -0.404601  0.328231 -0.606089
27  0.673649  0.711884 -0.995402 -0.289998
28  1.377468  1.007739 -0.325769 -0.063379
29  1.463852 -1.781127 -1.837464  1.158597
..       ...       ...       ...       ...
70 -1.401465  0.573155 -0.235814  0.068138
71  0.929408 -0.689281 -0.205336 -0.905672
72  0.934227 -0.777389 -0.384225 -0.271023
73  0.742026  0.670250 -1.266047 -0.416933
74  1.280917 -1.524092  0.240978 -0.046154
75 -0.247280  1.267432  1.200601  1.750099
76 -0.900641  1.819398 -1.047033 -0.981987
77 -1.113925  0.376577  0.961469  0.765957
78 -0.939734  0.230127  0.044722  1.143659
79  0.733179  0.225056  0.312824  0.239488
80 -0.397156  0.311949 -0.905166  0.113107
81  1.126771  0.651729  1.535810 -1.627943
82  0.143667 -0.245705 -0.442914  0.229740
83 -0.029928 -0.730545 -0.724271  0.227002
84  2.446878  0.089425  0.284990  0.077735
85 -0.629529  1.958686  1.235609 -0.667418
86 -1.287459  0.026937  1.756261  0.673879
87  1.598896 -0.204451 -0.516837 -0.146304
88  1.573955  1.139516  0.541662 -1.827490
89 -0.504609 -0.308055 -0.384849 -1.899596
90  0.840321 -0.851266  0.784558  0.154834
91  0.269118 -0.123110 -1.172403  1.194886
92 -0.364887 -0.834662  1.595909 -0.270123
93 -1.120425 -0.006423  0.954265  1.973064
94 -1.231210  1.241681 -0.706597 -0.625969
95  2.110900  1.249678 -0.748439 -0.924050
96 -0.260504 -1.591289 -0.276982 -0.182658
97  1.792435  1.057695 -0.892087 -1.912645
98  0.572616  0.264947 -1.152135  0.734517
99  0.981145  0.323019 -2.422532  0.763140

[100 rows x 4 columns]

### Task 12: Check the number of rows and columns of just created dataframe 'df' (1 point)

In [5]:
## Type your code below
df.shape

(100, 4)

### Task 13: Display the first 10 rows and last 8 rows of 'df' (2 points)

In [8]:
#first 10 rows of df
## Type your code below
df.head(10)

          A         B         C         D
0 -0.084911 -0.795485  1.581481  1.015433
1 -1.410677  0.103373  0.447437  2.182503
2  0.516016  0.720781  1.895498  0.210154
3 -1.008897 -0.752169 -0.338768  2.157013
4  1.029759  0.944237 -1.011756 -1.000923
5  2.641783 -0.985823  1.497767 -0.685855
6 -1.126254  0.963541  0.090009 -0.196320
7  2.400778 -1.050521  0.879870  0.687032
8  1.079135  0.596002 -0.056304 -2.353390
9 -1.055603  0.179866  2.688573 -0.459659

In [9]:
# last 8 rows of df
## Type your code below
df.tail(8)

           A         B         C         D
92 -0.075723 -0.499385  0.746428 -0.143847
93 -0.250212 -2.260829  0.487173 -0.859944
94  0.546218 -0.887996  1.958019 -1.220224
95  0.952042  0.869659  0.057128  0.076998
96  1.313127  0.149335 -0.433879 -0.292120
97  0.865445  0.449495  0.117858  1.017658
98 -0.609567  0.232678  0.302282  0.656716
99  0.769916 -0.636590  1.283663 -0.521084

### Task 14: Display the column names of 'df' (1 point)

In [11]:
## Type your code below
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

### Task 15: Display quick statistic summary of 'df' (2 points)

In [12]:
## Type your code below
df.describe()

                A           B           C           D
count  100.000000  100.000000  100.000000  100.000000
mean     0.055773    0.016642    0.023439   -0.072689
std      1.033220    0.969294    1.000856    1.049070
min     -3.136552   -2.260829   -2.769516   -2.634938
25%     -0.684266   -0.688767   -0.708167   -0.688639
50%      0.095153    0.163600    0.036422   -0.248490
75%      0.818181    0.615194    0.509148    0.664295
max      2.641783    2.776889    2.688573    3.349875

### Task 16: Sort values by column C descendingly (2 points)

In [16]:
## Type your code below

df.sort_values(by='C', ascending=False)

           A         B         C         D
36 -0.593333 -2.425986  2.507904  0.141278
62 -1.938561 -0.668516  2.358208 -0.209906
46 -0.564554  0.780704  2.253451  0.979557
32  0.254603 -0.690124  1.893345  1.597959
65 -0.266601 -0.173295  1.891475  0.035177
86 -1.287459  0.026937  1.756261  0.673879
66 -0.042660 -0.515793  1.724217  0.294942
63 -0.740359 -1.634125  1.712490  0.629780
92 -0.364887 -0.834662  1.595909 -0.270123
37 -0.551970  0.058346  1.576324 -0.455353
81  1.126771  0.651729  1.535810 -1.627943
18  0.983469  0.986837  1.502318 -1.372833
59 -0.418419 -1.512697  1.494540 -0.243002
56 -1.878911 -0.115218  1.422339 -1.011491
5  -0.484932 -0.169802  1.321495  1.086461
85 -0.629529  1.958686  1.235609 -0.667418
17 -0.808849  1.741419  1.207683  1.083034
75 -0.247280  1.267432  1.200601  1.750099
33 -0.202451 -0.909123  1.136698 -0.676459
6   0.255714  0.356519  1.098574  0.206833
10  1.202771  0.201301  1.092457  0.029396
60 -2.212365 -0.078845  0.971114 -0.087307
77 -1.113925  0.376577  0.961469  0.765957
93 -1.120425 -0.006423  0.954265  1.973064
9   0.005959 -2.046826  0.879997 -0.424316
35  2.805482 -1.005001  0.810446 -0.200542
90  0.840321 -0.851266  0.784558  0.154834
61 -0.692920 -0.932792  0.598553  1.313880
88  1.573955  1.139516  0.541662 -1.827490
13  0.763835  0.042963  0.408237  0.378144
..       ...       ...       ...       ...
69 -0.508196 -0.194670 -0.631169  0.348329
15  0.818140 -1.097522 -0.696077  0.626603
94 -1.231210  1.241681 -0.706597 -0.625969
83 -0.029928 -0.730545 -0.724271  0.227002
0  -0.140695 -0.070902 -0.745727  2.279679
95  2.110900  1.249678 -0.748439 -0.924050
43  0.546842 -0.469388 -0.787541 -1.100184
7   0.356424 -1.852580 -0.801042 -0.071295
25 -0.096058  0.553555 -0.823377 -1.244841
57  0.060991 -0.616811 -0.843210 -0.089853
97  1.792435  1.057695 -0.892087 -1.912645
49  0.683374 -0.529340 -0.892776  1.965617
80 -0.397156  0.311949 -0.905166  0.113107
27  0.673649  0.711884 -0.995402 -0.289998
76 -0.900641  1.819398 -1.047033 -0.981987
98  0.572616  0.264947 -1.152135  0.734517
91  0.269118 -0.123110 -1.172403  1.194886
41 -1.609016  1.077040 -1.210020  0.854720
64  0.127903 -1.317744 -1.218983 -0.753740
2  -0.505161  0.018143 -1.246864  1.463367
73  0.742026  0.670250 -1.266047 -0.416933
52  0.239762 -1.457672 -1.292647 -1.048721
22  1.112666  0.197965 -1.299121  1.782092
8   1.270059  1.351365 -1.303072  2.019604
53  0.351301  1.776262 -1.320830  0.609839
39  0.420549  0.486980 -1.323598 -0.483852
54  0.890539  0.849878 -1.590839  1.273934
4   1.201521 -0.296916 -1.827800  0.647047
29  1.463852 -1.781127 -1.837464  1.158597
99  0.981145  0.323019 -2.422532  0.763140

[100 rows x 4 columns]

### Task 17: Create a new dataframe 'df2' that contains the first 50 rows, and second and fourth columns. (2 Points)
Hint:
1. use .iloc[,] remember the index starts at 0.

In [18]:
## Type your code below

df2 = df.iloc[:50,[1,3]]
df2

           B         D
0  -0.070902  2.279679
1   1.258383 -0.794149
2   0.018143  1.463367
3  -0.041728 -1.206658
4  -0.296916  0.647047
5  -0.169802  1.086461
6   0.356519  0.206833
7  -1.852580 -0.071295
8   1.351365  2.019604
9  -2.046826 -0.424316
10  0.201301  0.029396
11  0.712354 -0.667935
12  0.303580 -0.527033
13  0.042963  0.378144
14 -1.439284  1.063746
15 -1.097522  0.626603
16 -0.844104  1.120905
17  1.741419  1.083034
18  0.986837 -1.372833
19  0.149933 -0.999220
20 -0.145871  2.072823
21 -1.250003 -2.064275
22  0.197965  1.782092
23 -0.864650  0.177945
24 -0.247094  0.307330
25  0.553555 -1.244841
26 -0.404601 -0.606089
27  0.711884 -0.289998
28  1.007739 -0.063379
29 -1.781127  1.158597
30  1.183316 -0.481969
31  1.268915 -0.486316
32 -0.690124  1.597959
33 -0.909123 -0.676459
34 -0.005455 -1.037591
35 -1.005001 -0.200542
36 -2.425986  0.141278
37  0.058346 -0.455353
38 -1.457418  0.634054
39  0.486980 -0.483852
40  0.650230 -1.816325
41  1.077040  0.854720
42  0.168469  1.059110
43 -0.469388 -1.100184
44 -0.814195 -1.007406
45 -0.697694  0.108677
46  0.780704  0.979557
47 -0.062631  0.866793
48 -0.251142  1.431545
49 -0.529340  1.965617

### Task 18: Select rows of 'df' where column B's value is greater than 0. (2 points)

In [19]:
## Type your code below

df[df.B > 0]

           A         B         C         D
1  -0.255268  1.258383 -0.345450 -0.794149
2  -0.505161  0.018143 -1.246864  1.463367
6   0.255714  0.356519  1.098574  0.206833
8   1.270059  1.351365 -1.303072  2.019604
10  1.202771  0.201301  1.092457  0.029396
11 -0.445036  0.712354 -0.117799 -0.667935
12 -1.332635  0.303580 -0.576803 -0.527033
13  0.763835  0.042963  0.408237  0.378144
17 -0.808849  1.741419  1.207683  1.083034
18  0.983469  0.986837  1.502318 -1.372833
19 -1.954546  0.149933 -0.024339 -0.999220
22  1.112666  0.197965 -1.299121  1.782092
25 -0.096058  0.553555 -0.823377 -1.244841
27  0.673649  0.711884 -0.995402 -0.289998
28  1.377468  1.007739 -0.325769 -0.063379
30 -0.223187  1.183316 -0.133791 -0.481969
31 -1.070012  1.268915 -0.013145 -0.486316
37 -0.551970  0.058346  1.576324 -0.455353
39  0.420549  0.486980 -1.323598 -0.483852
40 -0.422000  0.650230 -0.436785 -1.816325
41 -1.609016  1.077040 -1.210020  0.854720
42 -1.767461  0.168469  0.139989  1.059110
46 -0.564554  0.780704  2.253451  0.979557
50  1.261877  1.213901  0.040846 -0.175494
51 -1.135556  0.192954 -0.033514  2.715161
53  0.351301  1.776262 -1.320830  0.609839
54  0.890539  0.849878 -1.590839  1.273934
58 -2.029053  0.133409  0.058143  0.617994
67  1.228619  1.028012 -0.623733 -0.460729
70 -1.401465  0.573155 -0.235814  0.068138
73  0.742026  0.670250 -1.266047 -0.416933
75 -0.247280  1.267432  1.200601  1.750099
76 -0.900641  1.819398 -1.047033 -0.981987
77 -1.113925  0.376577  0.961469  0.765957
78 -0.939734  0.230127  0.044722  1.143659
79  0.733179  0.225056  0.312824  0.239488
80 -0.397156  0.311949 -0.905166  0.113107
81  1.126771  0.651729  1.535810 -1.627943
84  2.446878  0.089425  0.284990  0.077735
85 -0.629529  1.958686  1.235609 -0.667418
86 -1.287459  0.026937  1.756261  0.673879
88  1.573955  1.139516  0.541662 -1.827490
94 -1.231210  1.241681 -0.706597 -0.625969
95  2.110900  1.249678 -0.748439 -0.924050
97  1.792435  1.057695 -0.892087 -1.912645
98  0.572616  0.264947 -1.152135  0.734517
99  0.981145  0.323019 -2.422532  0.763140

### Task 19: Creat a new dataframe 'df3' that converts all negative numbers and zeros into positive (2 points)
Hint:
1. Make a copy of df using .copy()

In [25]:
## Type your code below

df3 = df.copy()
df3[df3 <= 0] = df3.abs()

df3

           A         B         C         D
0   0.140695  0.070902  0.745727  2.279679
1   0.255268  1.258383  0.345450  0.794149
2   0.505161  0.018143  1.246864  1.463367
3   0.014510  0.041728  0.266508  1.206658
4   1.201521  0.296916  1.827800  0.647047
5   0.484932  0.169802  1.321495  1.086461
6   0.255714  0.356519  1.098574  0.206833
7   0.356424  1.852580  0.801042  0.071295
8   1.270059  1.351365  1.303072  2.019604
9   0.005959  2.046826  0.879997  0.424316
10  1.202771  0.201301  1.092457  0.029396
11  0.445036  0.712354  0.117799  0.667935
12  1.332635  0.303580  0.576803  0.527033
13  0.763835  0.042963  0.408237  0.378144
14  1.449420  1.439284  0.492395  1.063746
15  0.818140  1.097522  0.696077  0.626603
16  0.274742  0.844104  0.393274  1.120905
17  0.808849  1.741419  1.207683  1.083034
18  0.983469  0.986837  1.502318  1.372833
19  1.954546  0.149933  0.024339  0.999220
20  1.233681  0.145871  0.559328  2.072823
21  0.962003  1.250003  0.443778  2.064275
22  1.112666  0.197965  1.299121  1.782092
23  1.317219  0.864650  0.363672  0.177945
24  0.740232  0.247094  0.280931  0.307330
25  0.096058  0.553555  0.823377  1.244841
26  1.838482  0.404601  0.328231  0.606089
27  0.673649  0.711884  0.995402  0.289998
28  1.377468  1.007739  0.325769  0.063379
29  1.463852  1.781127  1.837464  1.158597
..       ...       ...       ...       ...
70  1.401465  0.573155  0.235814  0.068138
71  0.929408  0.689281  0.205336  0.905672
72  0.934227  0.777389  0.384225  0.271023
73  0.742026  0.670250  1.266047  0.416933
74  1.280917  1.524092  0.240978  0.046154
75  0.247280  1.267432  1.200601  1.750099
76  0.900641  1.819398  1.047033  0.981987
77  1.113925  0.376577  0.961469  0.765957
78  0.939734  0.230127  0.044722  1.143659
79  0.733179  0.225056  0.312824  0.239488
80  0.397156  0.311949  0.905166  0.113107
81  1.126771  0.651729  1.535810  1.627943
82  0.143667  0.245705  0.442914  0.229740
83  0.029928  0.730545  0.724271  0.227002
84  2.446878  0.089425  0.284990  0.077735
85  0.629529  1.958686  1.235609  0.667418
86  1.287459  0.026937  1.756261  0.673879
87  1.598896  0.204451  0.516837  0.146304
88  1.573955  1.139516  0.541662  1.827490
89  0.504609  0.308055  0.384849  1.899596
90  0.840321  0.851266  0.784558  0.154834
91  0.269118  0.123110  1.172403  1.194886
92  0.364887  0.834662  1.595909  0.270123
93  1.120425  0.006423  0.954265  1.973064
94  1.231210  1.241681  0.706597  0.625969
95  2.110900  1.249678  0.748439  0.924050
96  0.260504  1.591289  0.276982  0.182658
97  1.792435  1.057695  0.892087  1.912645
98  0.572616  0.264947  1.152135  0.734517
99  0.981145  0.323019  2.422532  0.763140

[100 rows x 4 columns]

### Task 20:  Use .apply() to calculate the logs of all values in 'df3'  (2 points)
Hint:
1. Use .apply()
2. apply np.log function

In [30]:
## Type your code below

df3.apply(np.log)

           A         B         C         D
0  -1.961162 -2.646461 -0.293396  0.824035
1  -1.365440  0.229827 -1.062908 -0.230484
2  -0.682878 -4.009497  0.220632  0.380740
3  -4.232916 -3.176590 -1.322353  0.187855
4   0.183588 -1.214308  0.603113 -0.435336
5  -0.723746 -1.773123  0.278764  0.082926
6  -1.363697 -1.031369  0.094013 -1.575845
7  -1.031635  0.616579 -0.221842 -2.640924
8   0.239063  0.301115  0.264724  0.702901
9  -5.122864  0.716290 -0.127836 -0.857276
10  0.184628 -1.602956  0.088430 -3.526908
11 -0.809600 -0.339180 -2.138775 -0.403565
12  0.287158 -1.192109 -0.550254 -0.640492
13 -0.269404 -3.147407 -0.895906 -0.972481
14  0.371163  0.364145 -0.708475  0.061796
15 -0.200722  0.093055 -0.362295 -0.467442
16 -1.291923 -0.169480 -0.933249  0.114137
17 -0.212144  0.554700  0.188704  0.079766
18 -0.016670 -0.013250  0.407009  0.316877
19  0.670158 -1.897568 -3.715668 -0.000780
20  0.210002 -1.925031 -0.581020  0.728912
21 -0.038738  0.223146 -0.812431  0.724779
22  0.106759 -1.619667  0.261688  0.577788
23  0.275522 -0.145430 -1.011502 -1.726281
24 -0.300791 -1.397985 -1.269645 -1.179833
25 -2.342798 -0.591394 -0.194341  0.219008
26  0.608940 -0.904855 -1.114037 -0.500729
27 -0.395045 -0.339841 -0.004609 -1.237882
28  0.320247  0.007709 -1.121568 -2.758615
29  0.381071  0.577246  0.608386  0.147209
..       ...       ...       ...       ...
70  0.337518 -0.556600 -1.444713 -2.686222
71 -0.073208 -0.372106 -1.583107 -0.099078
72 -0.068036 -0.251814 -0.956527 -1.305552
73 -0.298371 -0.400105  0.235899 -0.874830
74  0.247576  0.421399 -1.423049 -3.075777
75 -1.397233  0.236993  0.182822  0.559672
76 -0.104649  0.598506  0.045960 -0.018177
77  0.107890 -0.976633 -0.039293 -0.266629
78 -0.062159 -1.469122 -3.107281  0.134233
79 -0.310366 -1.491404 -1.162114 -1.429254
80 -0.923425 -1.164917 -0.099637 -2.179424
81  0.119356 -0.428127  0.429058  0.487317
82 -1.940256 -1.403623 -0.814379 -1.470807
83 -3.508964 -0.313965 -0.322589 -1.482796
84  0.894813 -2.414360 -1.255302 -2.554454
85 -0.462783  0.672274  0.211564 -0.404339
86  0.252671 -3.614240  0.563187 -0.394704
87  0.469313 -1.587428 -0.660028 -1.922072
88  0.453592  0.130604 -0.613113  0.602943
89 -0.683971 -1.177476 -0.954904  0.641641
90 -0.173971 -0.161030 -0.242635 -1.865403
91 -1.312607 -2.094681  0.159055  0.178051
92 -1.008166 -0.180728  0.467443 -1.308878
93  0.113708 -5.047876 -0.046814  0.679588
94  0.207998  0.216466 -0.347295 -0.468455
95  0.747114  0.222886 -0.289765 -0.078989
96 -1.345136  0.464544 -1.283803 -1.700141
97  0.583575  0.056092 -0.114192  0.648487
98 -0.557540 -1.328225  0.141617 -0.308542
99 -0.019035 -1.130045  0.884813 -0.270314

[100 rows x 4 columns]

### Task 21: Writing df3 to 'df3.csv' into a csv file in the current directory (2 points)
Hint:
1. use `index = False`

In [31]:
## Type your code below

df3.to_csv('df3.csv',index=False)